/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.5/userguide/multi_project_builds.html
 */

rootProject.name = "energy-monitor-hivemq-extension"

pluginManagement {
    plugins {
         id("com.hivemq.extension") version "2.1.0"
    }
}