/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.energymonitor.extension;

import com.hivemq.extension.sdk.api.ExtensionMain;
import com.hivemq.extension.sdk.api.annotations.NotNull;
import com.hivemq.extension.sdk.api.events.EventRegistry;
import com.hivemq.extension.sdk.api.parameter.*;
import com.hivemq.extension.sdk.api.services.Services;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App implements ExtensionMain {
    private static final @NotNull Logger log = LoggerFactory.getLogger(App.class);

    @Override
    public void extensionStart(@NotNull ExtensionStartInput extensionStartInput, @NotNull ExtensionStartOutput extensionStartOutput) {
        final ExtensionInformation extensionInformation = extensionStartInput.getExtensionInformation();
        log.info("Started " + extensionInformation.getName() + ":" + extensionInformation.getVersion());

        try {
            // setup authentication
            Services.securityRegistry().setAuthenticatorProvider(new EnergyMonitorAuthenticatorProvider());

            // add lifecycle event listeners
            final EventRegistry eventRegistry = Services.eventRegistry();
            final EnergyMonitorListeners energyMonitorListeners = new EnergyMonitorListeners();

            eventRegistry.setClientLifecycleEventListener(input -> energyMonitorListeners);

        } catch (Exception e) {
            log.error("Exception thrown at extension start: ", e);
        }
    }

    @Override
    public void extensionStop(@NotNull ExtensionStopInput extensionStopInput, @NotNull ExtensionStopOutput extensionStopOutput) {
        final ExtensionInformation extensionInformation = extensionStopInput.getExtensionInformation();
        log.info("Stopped " + extensionInformation.getName() + ":" + extensionInformation.getVersion());

    }
}
