/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.energymonitor.extension;

import com.hivemq.extension.sdk.api.ExtensionMain;
import com.hivemq.extension.sdk.api.annotations.NotNull;
import com.hivemq.extension.sdk.api.parameter.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App implements ExtensionMain {
    private static final @NotNull Logger log = LoggerFactory.getLogger(App.class);

    @Override
    public void extensionStart(@NotNull ExtensionStartInput extensionStartInput, @NotNull ExtensionStartOutput extensionStartOutput) {
        final ExtensionInformation extensionInformation = extensionStartInput.getExtensionInformation();
        log.info("Started " + extensionInformation.getName() + ":" + extensionInformation.getVersion());
    }

    @Override
    public void extensionStop(@NotNull ExtensionStopInput extensionStopInput, @NotNull ExtensionStopOutput extensionStopOutput) {
        final ExtensionInformation extensionInformation = extensionStopInput.getExtensionInformation();
        log.info("Stopped " + extensionInformation.getName() + ":" + extensionInformation.getVersion());

    }
}
